name: Build Typst document
on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
      - run: typst compile index.typ index.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: index.pdf

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y.%m.%d)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ env.DATE }}"
          files: main.pdf
      
